### ISSUE TITLE
`npm test`: unit tests fail for github&npm

### ISSUE THREAD

**Issue by GerHobbelt** [dylang/changelog#43]
These fail:

```

  github
    1) should have something come back for changelog
    2) should have something come back for commit messages

  npm
    3) should have something come back for pageHistory
```

**Comment by rarkins** [comment]
Don't these pass on Travis though? e.g. in your recent PRs, I click through to Travis results and see:

![image](https://user-images.githubusercontent.com/6311784/31159958-1cd1e8e2-a8cd-11e7-9335-022ffbd1543b.png)

**Comment by GerHobbelt** [comment]
~hmmmmm. It broke on the local box, so that must a local issue then? *drat!*~

See https://travis-ci.org/GerHobbelt/changelog/jobs/283166205: changelog b0rks on Node 6 and above.

Will do a quick pullreq for travisci too, so you can see it happen.

**Comment by GerHobbelt** [comment]
Found where it goes haywire. See commit referenced above.

output:

```
  github
    1) should have something come back for changelog
    2) should have something come back for commit messages

  npm
    3) should have something come back for pageHistory

  npm
    √ should return everything with no filter
    √ should return everything with filter all
    √ should return latest with filter latest
    √ should return matching single one with semver filter
    √ should return matching several with semver filter


  5 passing (83ms)
  3 pending
  3 failing

  1) github
       should have something come back for changelog:
     Uncaught Error: Invalid Chai property: object
    at Object.proxyGetter [as get] (node_modules\chai\lib\chai\utils\proxify.js:66:17)
    at test\github.test.js:15:37
    at _fulfilled (node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (node_modules\q\q.js:796:13)
    at node_modules\q\q.js:604:44
    at runSingle (node_modules\q\q.js:137:13)
    at flush (node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)


  2) github
       should have something come back for commit messages:
     Uncaught Error: Invalid Chai property: object
    at Object.proxyGetter [as get] (node_modules\chai\lib\chai\utils\proxify.js:66:17)
    at test\github.test.js:23:37
    at _fulfilled (node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (node_modules\q\q.js:796:13)
    at node_modules\q\q.js:556:49
    at runSingle (node_modules\q\q.js:137:13)
    at flush (node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)


  3) npm
       should have something come back for pageHistory:
     Uncaught Error: Invalid Chai property: object
    at Object.proxyGetter [as get] (node_modules\chai\lib\chai\utils\proxify.js:66:17)
    at test\npm.test.js:15:37
    at _fulfilled (node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (node_modules\q\q.js:796:13)
    at node_modules\q\q.js:556:49
    at runSingle (node_modules\q\q.js:137:13)
    at flush (node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)

```
