### ISSUE TITLE
Not work for scoped packages

### ISSUE THREAD

**Issue by vovkasm** [dylang/changelog#50]
Test case:
`changelog @types/react-native`
Results:
```
/usr/local/lib/node_modules/changelog/node_modules/q/q.js:155
                throw e;
                ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:106:11)
    at Object.urlParse [as parse] (url.js:100:13)
    at commitMessages (/usr/local/lib/node_modules/changelog/lib/datasrc/github.js:19:23)
    at _fulfilled (/usr/local/lib/node_modules/changelog/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/changelog/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/changelog/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/changelog/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/changelog/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/changelog/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
Expected results: show changelog

Environment:
- macOS 10.12.6
- node 9.3.0
- changelog 1.4.1

**Comment by GerHobbelt** [comment]
https://www.npmjs.com/package/@gerhobbelt/changelog : that one works (at least it does for my own scoped npm packages) 😄
